#!/usr/bin/bash

## execute checksec against all ELF objects currently installed
## according to https://fedoraproject.org/wiki/Changes/Harden_All_Packages
## Running checksec should always report only 
## Full RELRO Canary found NX enabled PIE enabled No RPATH No RUNPATH

## Partial RELRO and No canary found will be considered bugs:
## fweimer: Patial RELRO is likely a bug.
## fweimer: No canary found can also happen if the DSO is empty.
## fweimer: Or contains only functions which do not need stack protector instrumentation.
## atodorov: how about binaries ?
## fweimer: Same thing, except that small binaries are rare, so No canary found is even more likely a bug.

## Partial vs Full RELRO info:
## http://tk-blog.blogspot.bg/2009/02/relro-not-so-well-known-memory.html

## for stack canaries see:
## systemd-cat -t "checksec-collect" echo "WORKING DIR CHANGED TO" 

## NX memory protection:
## https://en.wikipedia.org/wiki/NX_bit#Linux

## PIE
## https://securityblog.redhat.com/2012/11/28/position-independent-executables-pie/

## RPATH and RUNPATH
## https://fedoraproject.org/wiki/Packaging:Guidelines#Beware_of_Rpath
## http://blog.tremily.us/posts/rpath/

function doLog {
    systemd-cat -t "checksec-collect" echo "$1"
}

previous_rpm=""

DIR="$1"
if [ -z "$DIR" ]; then
    DIR=`pwd`
fi

for r in `find "$DIR" -name "*.x86_64.rpm" | sort`; do
    NAME=`rpm -qp $r --qf "%{name}\n" 2>/dev/null`
    SOURCE=`rpm -qp $r --qf "%{SOURCERPM}\n" 2>/dev/null`
    TMPDIR=`mktemp -d /tmp/$NAME-XXXXX`
    doLog "inspecting $NAME in $TMPDIR"
    pushd $TMPDIR >/dev/null
    rpm2cpio $r | cpio -i -d 2>/dev/null

    for f in `find -type f | sort`; do
        file $f | grep "ELF" >/dev/null
        if [ $? -eq 0 ]; then
            output=`checksec --file $f | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" | \
                    grep -v "RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH      FILE"`
            # fweimer: Yes, that's expected, DSOs on x86_64 are always position-independent.
            cnt=`echo "$output" | \
                grep -v "Full RELRO      Canary found      NX enabled    PIE enabled     No RPATH   No RUNPATH" | \
                grep -v "Full RELRO      Canary found      NX enabled    DSO             No RPATH   No RUNPATH" | \
                wc -l`

            if [ $cnt -gt 0 ]; then # failure found
                # check for RPATH failure
                rcnt=`echo "$output" | \
                sed "s/Full RELRO//" | sed "s/Canary found//" | sed "s/NX enabled//" | sed "s/No RPATH//" | sed "s/No RUNPATH//" | \
                sed "s/DSO//" | sed "s/PIE enabled//" | tr -s " " | grep "^ RPATH \./" | wc -l`

                # RPATH found => exclude acceptable RPATH locations
                if [ $rcnt -gt 0 ]; then
                    cnt=`readelf -d $f | grep RPATH | grep -v "/usr/lib.*/.*" | wc -l`
                fi
            fi

            if [ $cnt -gt 0 ]; then # failure found
                if [ "$previous_rpm" != "$r" ]; then
                    previous_rpm=$r
                    echo
                    echo
                    echo
                    echo "----------"
                    echo $SOURCE
                    echo "$r"
                    echo "RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH      FILE"
                fi
                echo "$output"
            fi
        fi
    done

    popd >/dev/null
    rm -rf $TMPDIR
done
